name: Deploy to EC2

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Deploy to EC2 via SSH
        uses: appleboy/ssh-action@v1.0.3
        with:
          host: ${{ secrets.EC2_HOST }}
          username: ${{ secrets.EC2_USER }}
          key: ${{ secrets.EC2_SSH_KEY }}
          script: |
            cd ~/app
            git pull origin main || (rm -rf ~/app && git clone https://github.com/Abhishek25singh25/devops-assignment.git ~/app && cd ~/app)
            npm install
            sudo pm2 restart devops-app || sudo pm2 start app.js --name devops-app
            sudo pm2 save